### Obtener todos los usuarios
GET http://localhost:9000/api/obtenerUsuario

### Crear producto
POST http://localhost:9000/api/crearUsuario


### Actualizar un usuario por ID
PUT http://localhost:9000/api/modificarUsuario/:_id

### Eliminar un usuario por ID
DELETE http://localhost:9000/api/eliminarusuario/:_id